name: Daily Gym Reservation

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 05:00 UTC

jobs:
  run-reservation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium colorama tqdm

      - name: Download ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb
          wget -N https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run autoReservation.py
        env:
          TIME_OPTION: '1'  # Set your desired time option here
          CURRENT_DAY: 'Monday'  # Set the desired day here
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          python autoReservation.py $TIME_OPTION $CURRENT_DAY
